# Generated by Django 4.0.5 on 2022-06-16 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=200)),
                ('descripcion', models.CharField(max_length=500)),
                ('fecha', models.DateField()),
                ('estado', models.CharField(max_length=100)),
                ('codigoBarra', models.UUIDField()),
            ],
        ),
    ]
