# Generated by Django 4.0.5 on 2022-06-16 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payapi', '0002_remove_boleta_id_alter_boleta_codigobarra'),
    ]

    operations = [
        migrations.AddField(
            model_name='boleta',
            name='importe',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
